package com.jme3.ai.navigation.utils;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
public class BooleanArray {

    private long swigCPtr;
    protected boolean swigCMemOwn;

    public BooleanArray(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    public static long getCPtr(BooleanArray obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                RecastJNI.delete_BooleanArray(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public BooleanArray(int nelements) {
        this(RecastJNI.new_BooleanArray(nelements), true);
    }

    public boolean getitem(int index) {
        return RecastJNI.BooleanArray_getitem(swigCPtr, this, index);
    }

    public void setitem(int index, boolean value) {
        RecastJNI.BooleanArray_setitem(swigCPtr, this, index, value);
    }

    public SWIGTYPE_p_bool cast() {
        long cPtr = RecastJNI.BooleanArray_cast(swigCPtr, this);
        return (cPtr == 0) ? null : new SWIGTYPE_p_bool(cPtr, false);
    }

    public static BooleanArray frompointer(SWIGTYPE_p_bool t) {
        long cPtr = RecastJNI.BooleanArray_frompointer(SWIGTYPE_p_bool.getCPtr(t));
        return (cPtr == 0) ? null : new BooleanArray(cPtr, false);
    }
}
