package com.jme3.ai.navigation.utils;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SWIGTYPE_p_void {
  private long swigCPtr;

  public SWIGTYPE_p_void(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  public SWIGTYPE_p_void() {
    swigCPtr = 0;
  }

  public static long getCPtr(SWIGTYPE_p_void obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

