package com.jme3.ai.recast.utils;

import com.jme3.ai.recast.utils.RecastJNI;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class rcIntArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public rcIntArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(rcIntArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_rcIntArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public rcIntArray() {
    this(RecastJNI.new_rcIntArray__SWIG_0(), true);
  }

  public rcIntArray(int n) {
    this(RecastJNI.new_rcIntArray__SWIG_1(n), true);
  }

  public void resize(int n) {
    RecastJNI.rcIntArray_resize(swigCPtr, this, n);
  }

  public void push(int item) {
    RecastJNI.rcIntArray_push(swigCPtr, this, item);
  }

  public int pop() {
    return RecastJNI.rcIntArray_pop(swigCPtr, this);
  }

  public int size() {
    return RecastJNI.rcIntArray_size(swigCPtr, this);
  }

}
