package com.jme3.ai.recast.utils;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class UCharArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public UCharArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(UCharArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @Override
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_UCharArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UCharArray(int nelements) {
    this(RecastJNI.new_UCharArray(nelements), true);
  }

  public short getitem(int index) {
    return RecastJNI.UCharArray_getitem(swigCPtr, this, index);
  }

  public void setitem(int index, short value) {
    RecastJNI.UCharArray_setitem(swigCPtr, this, index, value);
  }

  public SWIGTYPE_p_unsigned_char cast() {
    long cPtr = RecastJNI.UCharArray_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static UCharArray frompointer(SWIGTYPE_p_unsigned_char t) {
    long cPtr = RecastJNI.UCharArray_frompointer(SWIGTYPE_p_unsigned_char.getCPtr(t));
    return (cPtr == 0) ? null : new UCharArray(cPtr, false);
  }

}
