package com.jme3.ai.recast;

import com.jme3.ai.recast.utils.RecastJNI;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class BuildContoursFlags {
  public final static BuildContoursFlags RC_CONTOUR_TESS_WALL_EDGES = new BuildContoursFlags("RC_CONTOUR_TESS_WALL_EDGES", RecastJNI.RC_CONTOUR_TESS_WALL_EDGES_get());
  public final static BuildContoursFlags RC_CONTOUR_TESS_AREA_EDGES = new BuildContoursFlags("RC_CONTOUR_TESS_AREA_EDGES", RecastJNI.RC_CONTOUR_TESS_AREA_EDGES_get());

  public final int swigValue() {
    return swigValue;
  }

  @Override
  public String toString() {
    return swigName;
  }

  public static BuildContoursFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + BuildContoursFlags.class + " with value " + swigValue);
  }

  private BuildContoursFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private BuildContoursFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private BuildContoursFlags(String swigName, BuildContoursFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static BuildContoursFlags[] swigValues = { RC_CONTOUR_TESS_WALL_EDGES, RC_CONTOUR_TESS_AREA_EDGES };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

