package com.jme3.ai.recast;

import com.jme3.ai.recast.utils.RecastJNI;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
public class CompactSpan {

    private long swigCPtr;
    protected boolean swigCMemOwn;

    public CompactSpan(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    public static long getCPtr(CompactSpan obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    @Override
    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                RecastJNI.delete_rcCompactSpan(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public void setY(int value) {
        RecastJNI.rcCompactSpan_y_set(swigCPtr, this, value);
    }

    public int getY() {
        return RecastJNI.rcCompactSpan_y_get(swigCPtr, this);
    }

    public void setReg(int value) {
        RecastJNI.rcCompactSpan_reg_set(swigCPtr, this, value);
    }

    public int getReg() {
        return RecastJNI.rcCompactSpan_reg_get(swigCPtr, this);
    }

    public void setConnection(long value) {
        RecastJNI.rcCompactSpan_con_set(swigCPtr, this, value);
    }

    public long getConnection() {
        return RecastJNI.rcCompactSpan_con_get(swigCPtr, this);
    }

    public void setHeight(long value) {
        RecastJNI.rcCompactSpan_h_set(swigCPtr, this, value);
    }

    public long getHeight() {
        return RecastJNI.rcCompactSpan_h_get(swigCPtr, this);
    }

    private CompactSpan() {
        this(RecastJNI.new_rcCompactSpan(), true);
    }
}
