package com.jme3.ai.recast;

import com.jme3.ai.recast.utils.RecastJNI;
import com.jme3.ai.recast.utils.SWIGTYPE_p_float;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ContourSet {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ContourSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ContourSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_rcContourSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setConts(Contour value) {
    RecastJNI.rcContourSet_conts_set(swigCPtr, this, Contour.getCPtr(value), value);
  }

  public Contour getConts() {
    long cPtr = RecastJNI.rcContourSet_conts_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Contour(cPtr, false);
  }

  public void setNconts(int value) {
    RecastJNI.rcContourSet_nconts_set(swigCPtr, this, value);
  }

  public int getNconts() {
    return RecastJNI.rcContourSet_nconts_get(swigCPtr, this);
  }

  public void setBmin(SWIGTYPE_p_float value) {
    RecastJNI.rcContourSet_bmin_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getBmin() {
    long cPtr = RecastJNI.rcContourSet_bmin_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setBmax(SWIGTYPE_p_float value) {
    RecastJNI.rcContourSet_bmax_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getBmax() {
    long cPtr = RecastJNI.rcContourSet_bmax_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setCs(float value) {
    RecastJNI.rcContourSet_cs_set(swigCPtr, this, value);
  }

  public float getCs() {
    return RecastJNI.rcContourSet_cs_get(swigCPtr, this);
  }

  public void setCh(float value) {
    RecastJNI.rcContourSet_ch_set(swigCPtr, this, value);
  }

  public float getCh() {
    return RecastJNI.rcContourSet_ch_get(swigCPtr, this);
  }

  public void setWidth(int value) {
    RecastJNI.rcContourSet_width_set(swigCPtr, this, value);
  }

  public int getWidth() {
    return RecastJNI.rcContourSet_width_get(swigCPtr, this);
  }

  public void setHeight(int value) {
    RecastJNI.rcContourSet_height_set(swigCPtr, this, value);
  }

  public int getHeight() {
    return RecastJNI.rcContourSet_height_get(swigCPtr, this);
  }

  public void setBorderSize(int value) {
    RecastJNI.rcContourSet_borderSize_set(swigCPtr, this, value);
  }

  public int getBorderSize() {
    return RecastJNI.rcContourSet_borderSize_get(swigCPtr, this);
  }

  public ContourSet() {
    this(RecastJNI.new_rcContourSet(), true);
  }

}
