package com.jme3.ai.recast;

import com.jme3.ai.recast.utils.RecastJNI;
import com.jme3.ai.recast.utils.SWIGTYPE_p_int;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Contour {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Contour(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Contour obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_rcContour(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVerts(SWIGTYPE_p_int value) {
    RecastJNI.rcContour_verts_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getVerts() {
    long cPtr = RecastJNI.rcContour_verts_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setNverts(int value) {
    RecastJNI.rcContour_nverts_set(swigCPtr, this, value);
  }

  public int getNverts() {
    return RecastJNI.rcContour_nverts_get(swigCPtr, this);
  }

  public void setRverts(SWIGTYPE_p_int value) {
    RecastJNI.rcContour_rverts_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getRverts() {
    long cPtr = RecastJNI.rcContour_rverts_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setNrverts(int value) {
    RecastJNI.rcContour_nrverts_set(swigCPtr, this, value);
  }

  public int getNrverts() {
    return RecastJNI.rcContour_nrverts_get(swigCPtr, this);
  }

  public void setReg(int value) {
    RecastJNI.rcContour_reg_set(swigCPtr, this, value);
  }

  public int getReg() {
    return RecastJNI.rcContour_reg_get(swigCPtr, this);
  }

  public void setArea(short value) {
    RecastJNI.rcContour_area_set(swigCPtr, this, value);
  }

  public short getArea() {
    return RecastJNI.rcContour_area_get(swigCPtr, this);
  }

  public Contour() {
    this(RecastJNI.new_rcContour(), true);
  }

}
