package com.jme3.ai.recast;

import com.jme3.ai.recast.utils.RecastJNI;
import com.jme3.ai.recast.utils.SWIGTYPE_p_float;
import com.jme3.ai.recast.utils.SWIGTYPE_p_unsigned_char;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class HeightfieldLayer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public HeightfieldLayer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(HeightfieldLayer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_rcHeightfieldLayer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBmin(SWIGTYPE_p_float value) {
    RecastJNI.rcHeightfieldLayer_bmin_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getBmin() {
    long cPtr = RecastJNI.rcHeightfieldLayer_bmin_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setBmax(SWIGTYPE_p_float value) {
    RecastJNI.rcHeightfieldLayer_bmax_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getBmax() {
    long cPtr = RecastJNI.rcHeightfieldLayer_bmax_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setCs(float value) {
    RecastJNI.rcHeightfieldLayer_cs_set(swigCPtr, this, value);
  }

  public float getCs() {
    return RecastJNI.rcHeightfieldLayer_cs_get(swigCPtr, this);
  }

  public void setCh(float value) {
    RecastJNI.rcHeightfieldLayer_ch_set(swigCPtr, this, value);
  }

  public float getCh() {
    return RecastJNI.rcHeightfieldLayer_ch_get(swigCPtr, this);
  }

  public void setWidth(int value) {
    RecastJNI.rcHeightfieldLayer_width_set(swigCPtr, this, value);
  }

  public int getWidth() {
    return RecastJNI.rcHeightfieldLayer_width_get(swigCPtr, this);
  }

  public void setHeight(int value) {
    RecastJNI.rcHeightfieldLayer_height_set(swigCPtr, this, value);
  }

  public int getHeight() {
    return RecastJNI.rcHeightfieldLayer_height_get(swigCPtr, this);
  }

  public void setMinx(int value) {
    RecastJNI.rcHeightfieldLayer_minx_set(swigCPtr, this, value);
  }

  public int getMinx() {
    return RecastJNI.rcHeightfieldLayer_minx_get(swigCPtr, this);
  }

  public void setMaxx(int value) {
    RecastJNI.rcHeightfieldLayer_maxx_set(swigCPtr, this, value);
  }

  public int getMaxx() {
    return RecastJNI.rcHeightfieldLayer_maxx_get(swigCPtr, this);
  }

  public void setMiny(int value) {
    RecastJNI.rcHeightfieldLayer_miny_set(swigCPtr, this, value);
  }

  public int getMiny() {
    return RecastJNI.rcHeightfieldLayer_miny_get(swigCPtr, this);
  }

  public void setMaxy(int value) {
    RecastJNI.rcHeightfieldLayer_maxy_set(swigCPtr, this, value);
  }

  public int getMaxy() {
    return RecastJNI.rcHeightfieldLayer_maxy_get(swigCPtr, this);
  }

  public void setHmin(int value) {
    RecastJNI.rcHeightfieldLayer_hmin_set(swigCPtr, this, value);
  }

  public int getHmin() {
    return RecastJNI.rcHeightfieldLayer_hmin_get(swigCPtr, this);
  }

  public void setHmax(int value) {
    RecastJNI.rcHeightfieldLayer_hmax_set(swigCPtr, this, value);
  }

  public int getHmax() {
    return RecastJNI.rcHeightfieldLayer_hmax_get(swigCPtr, this);
  }

  public void setHeights(SWIGTYPE_p_unsigned_char value) {
    RecastJNI.rcHeightfieldLayer_heights_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getHeights() {
    long cPtr = RecastJNI.rcHeightfieldLayer_heights_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setAreas(SWIGTYPE_p_unsigned_char value) {
    RecastJNI.rcHeightfieldLayer_areas_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getAreas() {
    long cPtr = RecastJNI.rcHeightfieldLayer_areas_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setCons(SWIGTYPE_p_unsigned_char value) {
    RecastJNI.rcHeightfieldLayer_cons_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getCons() {
    long cPtr = RecastJNI.rcHeightfieldLayer_cons_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public HeightfieldLayer() {
    this(RecastJNI.new_rcHeightfieldLayer(), true);
  }

}
