package com.jme3.ai.recast;

import com.jme3.ai.recast.utils.RecastJNI;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class HeightfieldLayerSet {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public HeightfieldLayerSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(HeightfieldLayerSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_rcHeightfieldLayerSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLayers(HeightfieldLayer value) {
    RecastJNI.rcHeightfieldLayerSet_layers_set(swigCPtr, this, HeightfieldLayer.getCPtr(value), value);
  }

  public HeightfieldLayer getLayers() {
    long cPtr = RecastJNI.rcHeightfieldLayerSet_layers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new HeightfieldLayer(cPtr, false);
  }

  public void setNlayers(int value) {
    RecastJNI.rcHeightfieldLayerSet_nlayers_set(swigCPtr, this, value);
  }

  public int getNlayers() {
    return RecastJNI.rcHeightfieldLayerSet_nlayers_get(swigCPtr, this);
  }

  public HeightfieldLayerSet() {
    this(RecastJNI.new_rcHeightfieldLayerSet(), true);
  }

}
