package com.jme3.ai.recast;

import com.jme3.ai.recast.utils.RecastJNI;
import com.jme3.ai.recast.utils.SWIGTYPE_p_float;
import com.jme3.ai.recast.utils.SWIGTYPE_p_unsigned_char;
import com.jme3.ai.recast.utils.SWIGTYPE_p_unsigned_short;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PolyMesh {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public PolyMesh(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(PolyMesh obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_rcPolyMesh(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVerts(SWIGTYPE_p_unsigned_short value) {
    RecastJNI.rcPolyMesh_verts_set(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_short getVerts() {
    long cPtr = RecastJNI.rcPolyMesh_verts_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
  }

  public void setPolys(SWIGTYPE_p_unsigned_short value) {
    RecastJNI.rcPolyMesh_polys_set(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_short getPolys() {
    long cPtr = RecastJNI.rcPolyMesh_polys_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
  }

  public void setRegs(SWIGTYPE_p_unsigned_short value) {
    RecastJNI.rcPolyMesh_regs_set(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_short getRegs() {
    long cPtr = RecastJNI.rcPolyMesh_regs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
  }

  public void setFlags(SWIGTYPE_p_unsigned_short value) {
    RecastJNI.rcPolyMesh_flags_set(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_short getFlags() {
    long cPtr = RecastJNI.rcPolyMesh_flags_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
  }

  public void setAreas(SWIGTYPE_p_unsigned_char value) {
    RecastJNI.rcPolyMesh_areas_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getAreas() {
    long cPtr = RecastJNI.rcPolyMesh_areas_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setNverts(int value) {
    RecastJNI.rcPolyMesh_nverts_set(swigCPtr, this, value);
  }

  public int getNverts() {
    return RecastJNI.rcPolyMesh_nverts_get(swigCPtr, this);
  }

  public void setNpolys(int value) {
    RecastJNI.rcPolyMesh_npolys_set(swigCPtr, this, value);
  }

  public int getNpolys() {
    return RecastJNI.rcPolyMesh_npolys_get(swigCPtr, this);
  }

  public void setMaxpolys(int value) {
    RecastJNI.rcPolyMesh_maxpolys_set(swigCPtr, this, value);
  }

  public int getMaxpolys() {
    return RecastJNI.rcPolyMesh_maxpolys_get(swigCPtr, this);
  }

  public void setNvp(int value) {
    RecastJNI.rcPolyMesh_nvp_set(swigCPtr, this, value);
  }

  public int getNvp() {
    return RecastJNI.rcPolyMesh_nvp_get(swigCPtr, this);
  }

  public void setBmin(SWIGTYPE_p_float value) {
    RecastJNI.rcPolyMesh_bmin_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getBmin() {
    long cPtr = RecastJNI.rcPolyMesh_bmin_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setBmax(SWIGTYPE_p_float value) {
    RecastJNI.rcPolyMesh_bmax_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getBmax() {
    long cPtr = RecastJNI.rcPolyMesh_bmax_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setCs(float value) {
    RecastJNI.rcPolyMesh_cs_set(swigCPtr, this, value);
  }

  public float getCs() {
    return RecastJNI.rcPolyMesh_cs_get(swigCPtr, this);
  }

  public void setCh(float value) {
    RecastJNI.rcPolyMesh_ch_set(swigCPtr, this, value);
  }

  public float getCh() {
    return RecastJNI.rcPolyMesh_ch_get(swigCPtr, this);
  }

  public void setBorderSize(int value) {
    RecastJNI.rcPolyMesh_borderSize_set(swigCPtr, this, value);
  }

  public int getBorderSize() {
    return RecastJNI.rcPolyMesh_borderSize_get(swigCPtr, this);
  }

  public PolyMesh() {
    this(RecastJNI.new_rcPolyMesh(), true);
  }

}
