package com.jme3.ai.recast;

import com.jme3.ai.recast.utils.RecastJNI;
import com.jme3.ai.recast.utils.SWIGTYPE_p_float;
import com.jme3.ai.recast.utils.SWIGTYPE_p_unsigned_char;
import com.jme3.ai.recast.utils.SWIGTYPE_p_unsigned_int;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PolyMeshDetail {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public PolyMeshDetail(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(PolyMeshDetail obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_rcPolyMeshDetail(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMeshes(SWIGTYPE_p_unsigned_int value) {
    RecastJNI.rcPolyMeshDetail_meshes_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getMeshes() {
    long cPtr = RecastJNI.rcPolyMeshDetail_meshes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setVerts(SWIGTYPE_p_float value) {
    RecastJNI.rcPolyMeshDetail_verts_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getVerts() {
    long cPtr = RecastJNI.rcPolyMeshDetail_verts_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setTris(SWIGTYPE_p_unsigned_char value) {
    RecastJNI.rcPolyMeshDetail_tris_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getTris() {
    long cPtr = RecastJNI.rcPolyMeshDetail_tris_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setNmeshes(int value) {
    RecastJNI.rcPolyMeshDetail_nmeshes_set(swigCPtr, this, value);
  }

  public int getNmeshes() {
    return RecastJNI.rcPolyMeshDetail_nmeshes_get(swigCPtr, this);
  }

  public void setNverts(int value) {
    RecastJNI.rcPolyMeshDetail_nverts_set(swigCPtr, this, value);
  }

  public int getNverts() {
    return RecastJNI.rcPolyMeshDetail_nverts_get(swigCPtr, this);
  }

  public void setNtris(int value) {
    RecastJNI.rcPolyMeshDetail_ntris_set(swigCPtr, this, value);
  }

  public int getNtris() {
    return RecastJNI.rcPolyMeshDetail_ntris_get(swigCPtr, this);
  }

  public PolyMeshDetail() {
    this(RecastJNI.new_rcPolyMeshDetail(), true);
  }

}
