package com.jme3.ai.navigation.detour;

import com.jme3.ai.navigation.utils.RecastJNI;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
public final class StraightPathFlags {

    public final static StraightPathFlags DT_STRAIGHTPATH_START = new StraightPathFlags("DT_STRAIGHTPATH_START", RecastJNI.DT_STRAIGHTPATH_START_get());
    public final static StraightPathFlags DT_STRAIGHTPATH_END = new StraightPathFlags("DT_STRAIGHTPATH_END", RecastJNI.DT_STRAIGHTPATH_END_get());
    public final static StraightPathFlags DT_STRAIGHTPATH_OFFMESH_CONNECTION = new StraightPathFlags("DT_STRAIGHTPATH_OFFMESH_CONNECTION", RecastJNI.DT_STRAIGHTPATH_OFFMESH_CONNECTION_get());

    public final int swigValue() {
        return swigValue;
    }

    @Override
    public String toString() {
        return swigName;
    }

    public static StraightPathFlags swigToEnum(int swigValue) {
        if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue) {
            return swigValues[swigValue];
        }
        for (int i = 0; i < swigValues.length; i++) {
            if (swigValues[i].swigValue == swigValue) {
                return swigValues[i];
            }
        }
        throw new IllegalArgumentException("No enum " + StraightPathFlags.class + " with value " + swigValue);
    }

    private StraightPathFlags(String swigName) {
        this.swigName = swigName;
        this.swigValue = swigNext++;
    }

    private StraightPathFlags(String swigName, int swigValue) {
        this.swigName = swigName;
        this.swigValue = swigValue;
        swigNext = swigValue + 1;
    }

    private StraightPathFlags(String swigName, StraightPathFlags swigEnum) {
        this.swigName = swigName;
        this.swigValue = swigEnum.swigValue;
        swigNext = this.swigValue + 1;
    }
    private static StraightPathFlags[] swigValues = {DT_STRAIGHTPATH_START, DT_STRAIGHTPATH_END, DT_STRAIGHTPATH_OFFMESH_CONNECTION};
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
}
