package com.jme3.ai.navigation.crowd;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class dtAllocHint {
  public final static dtAllocHint DT_ALLOC_PERM = new dtAllocHint("DT_ALLOC_PERM");
  public final static dtAllocHint DT_ALLOC_TEMP = new dtAllocHint("DT_ALLOC_TEMP");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static dtAllocHint swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + dtAllocHint.class + " with value " + swigValue);
  }

  private dtAllocHint(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private dtAllocHint(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private dtAllocHint(String swigName, dtAllocHint swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static dtAllocHint[] swigValues = { DT_ALLOC_PERM, DT_ALLOC_TEMP };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

