package com.jme3.ai.navigation.crowd;


import com.jme3.ai.navigation.utils.SWIGTYPE_p_void;
import com.jme3.ai.navigation.utils.RecastJNI;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class dtCrowdAgentParams {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public dtCrowdAgentParams(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(dtCrowdAgentParams obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_dtCrowdAgentParams(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRadius(float value) {
    RecastJNI.dtCrowdAgentParams_radius_set(swigCPtr, this, value);
  }

  public float getRadius() {
    return RecastJNI.dtCrowdAgentParams_radius_get(swigCPtr, this);
  }

  public void setHeight(float value) {
    RecastJNI.dtCrowdAgentParams_height_set(swigCPtr, this, value);
  }

  public float getHeight() {
    return RecastJNI.dtCrowdAgentParams_height_get(swigCPtr, this);
  }

  public void setMaxAcceleration(float value) {
    RecastJNI.dtCrowdAgentParams_maxAcceleration_set(swigCPtr, this, value);
  }

  public float getMaxAcceleration() {
    return RecastJNI.dtCrowdAgentParams_maxAcceleration_get(swigCPtr, this);
  }

  public void setMaxSpeed(float value) {
    RecastJNI.dtCrowdAgentParams_maxSpeed_set(swigCPtr, this, value);
  }

  public float getMaxSpeed() {
    return RecastJNI.dtCrowdAgentParams_maxSpeed_get(swigCPtr, this);
  }

  public void setCollisionQueryRange(float value) {
    RecastJNI.dtCrowdAgentParams_collisionQueryRange_set(swigCPtr, this, value);
  }

  public float getCollisionQueryRange() {
    return RecastJNI.dtCrowdAgentParams_collisionQueryRange_get(swigCPtr, this);
  }

  public void setPathOptimizationRange(float value) {
    RecastJNI.dtCrowdAgentParams_pathOptimizationRange_set(swigCPtr, this, value);
  }

  public float getPathOptimizationRange() {
    return RecastJNI.dtCrowdAgentParams_pathOptimizationRange_get(swigCPtr, this);
  }

  public void setSeparationWeight(float value) {
    RecastJNI.dtCrowdAgentParams_separationWeight_set(swigCPtr, this, value);
  }

  public float getSeparationWeight() {
    return RecastJNI.dtCrowdAgentParams_separationWeight_get(swigCPtr, this);
  }

  public void setUpdateFlags(short value) {
    RecastJNI.dtCrowdAgentParams_updateFlags_set(swigCPtr, this, value);
  }

  public short getUpdateFlags() {
    return RecastJNI.dtCrowdAgentParams_updateFlags_get(swigCPtr, this);
  }

  public void setObstacleAvoidanceType(short value) {
    RecastJNI.dtCrowdAgentParams_obstacleAvoidanceType_set(swigCPtr, this, value);
  }

  public short getObstacleAvoidanceType() {
    return RecastJNI.dtCrowdAgentParams_obstacleAvoidanceType_get(swigCPtr, this);
  }

  public void setQueryFilterType(short value) {
    RecastJNI.dtCrowdAgentParams_queryFilterType_set(swigCPtr, this, value);
  }

  public short getQueryFilterType() {
    return RecastJNI.dtCrowdAgentParams_queryFilterType_get(swigCPtr, this);
  }

  public void setUserData(SWIGTYPE_p_void value) {
    RecastJNI.dtCrowdAgentParams_userData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUserData() {
    long cPtr = RecastJNI.dtCrowdAgentParams_userData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public dtCrowdAgentParams() {
    this(RecastJNI.new_dtCrowdAgentParams(), true);
  }

}
