package com.jme3.ai.navigation.crowd;


import com.jme3.ai.navigation.utils.SWIGTYPE_p_float;
import com.jme3.ai.navigation.utils.RecastJNI;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class dtCrowdAgentAnimation {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public dtCrowdAgentAnimation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(dtCrowdAgentAnimation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_dtCrowdAgentAnimation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setActive(boolean value) {
    RecastJNI.dtCrowdAgentAnimation_active_set(swigCPtr, this, value);
  }

  public boolean getActive() {
    return RecastJNI.dtCrowdAgentAnimation_active_get(swigCPtr, this);
  }

  public void setInitPos(SWIGTYPE_p_float value) {
    RecastJNI.dtCrowdAgentAnimation_initPos_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getInitPos() {
    long cPtr = RecastJNI.dtCrowdAgentAnimation_initPos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setStartPos(SWIGTYPE_p_float value) {
    RecastJNI.dtCrowdAgentAnimation_startPos_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getStartPos() {
    long cPtr = RecastJNI.dtCrowdAgentAnimation_startPos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setEndPos(SWIGTYPE_p_float value) {
    RecastJNI.dtCrowdAgentAnimation_endPos_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getEndPos() {
    long cPtr = RecastJNI.dtCrowdAgentAnimation_endPos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setPolyRef(long value) {
    RecastJNI.dtCrowdAgentAnimation_polyRef_set(swigCPtr, this, value);
  }

  public long getPolyRef() {
    return RecastJNI.dtCrowdAgentAnimation_polyRef_get(swigCPtr, this);
  }

  public void setT(float value) {
    RecastJNI.dtCrowdAgentAnimation_t_set(swigCPtr, this, value);
  }

  public float getT() {
    return RecastJNI.dtCrowdAgentAnimation_t_get(swigCPtr, this);
  }

  public void setTmax(float value) {
    RecastJNI.dtCrowdAgentAnimation_tmax_set(swigCPtr, this, value);
  }

  public float getTmax() {
    return RecastJNI.dtCrowdAgentAnimation_tmax_get(swigCPtr, this);
  }

  public dtCrowdAgentAnimation() {
    this(RecastJNI.new_dtCrowdAgentAnimation(), true);
  }

}
