package com.jme3.ai.navigation.crowd;


import com.jme3.ai.navigation.utils.RecastJNI;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class dtCrowdNeighbour {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public dtCrowdNeighbour(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(dtCrowdNeighbour obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_dtCrowdNeighbour(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIdx(int value) {
    RecastJNI.dtCrowdNeighbour_idx_set(swigCPtr, this, value);
  }

  public int getIdx() {
    return RecastJNI.dtCrowdNeighbour_idx_get(swigCPtr, this);
  }

  public void setDist(float value) {
    RecastJNI.dtCrowdNeighbour_dist_set(swigCPtr, this, value);
  }

  public float getDist() {
    return RecastJNI.dtCrowdNeighbour_dist_get(swigCPtr, this);
  }

  public dtCrowdNeighbour() {
    this(RecastJNI.new_dtCrowdNeighbour(), true);
  }

}
