package com.jme3.ai.navigation.crowd;


import com.jme3.ai.navigation.detour.NavMeshQuery;
import com.jme3.ai.navigation.detour.QueryFilter;
import com.jme3.ai.navigation.utils.SWIGTYPE_p_float;
import com.jme3.ai.navigation.utils.RecastJNI;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class dtLocalBoundary {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public dtLocalBoundary(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(dtLocalBoundary obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_dtLocalBoundary(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public dtLocalBoundary() {
    this(RecastJNI.new_dtLocalBoundary(), true);
  }

  public void reset() {
    RecastJNI.dtLocalBoundary_reset(swigCPtr, this);
  }

  public void update(long ref, SWIGTYPE_p_float pos, float collisionQueryRange, NavMeshQuery navquery, QueryFilter filter) {
    RecastJNI.dtLocalBoundary_update(swigCPtr, this, ref, SWIGTYPE_p_float.getCPtr(pos), collisionQueryRange, NavMeshQuery.getCPtr(navquery), navquery, QueryFilter.getCPtr(filter), filter);
  }

  public boolean isValid(NavMeshQuery navquery, QueryFilter filter) {
    return RecastJNI.dtLocalBoundary_isValid(swigCPtr, this, NavMeshQuery.getCPtr(navquery), navquery, QueryFilter.getCPtr(filter), filter);
  }

  public SWIGTYPE_p_float getCenter() {
    long cPtr = RecastJNI.dtLocalBoundary_getCenter(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public int getSegmentCount() {
    return RecastJNI.dtLocalBoundary_getSegmentCount(swigCPtr, this);
  }

  public SWIGTYPE_p_float getSegment(int i) {
    long cPtr = RecastJNI.dtLocalBoundary_getSegment(swigCPtr, this, i);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

}
