package com.jme3.ai.navigation.crowd;


import com.jme3.ai.navigation.utils.SWIGTYPE_p_float;
import com.jme3.ai.navigation.utils.RecastJNI;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class dtObstacleSegment {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public dtObstacleSegment(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(dtObstacleSegment obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_dtObstacleSegment(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setP(SWIGTYPE_p_float value) {
    RecastJNI.dtObstacleSegment_p_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getP() {
    long cPtr = RecastJNI.dtObstacleSegment_p_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setQ(SWIGTYPE_p_float value) {
    RecastJNI.dtObstacleSegment_q_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getQ() {
    long cPtr = RecastJNI.dtObstacleSegment_q_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setTouch(boolean value) {
    RecastJNI.dtObstacleSegment_touch_set(swigCPtr, this, value);
  }

  public boolean getTouch() {
    return RecastJNI.dtObstacleSegment_touch_get(swigCPtr, this);
  }

  public dtObstacleSegment() {
    this(RecastJNI.new_dtObstacleSegment(), true);
  }

}
