package com.jme3.ai.navigation.crowd;


import com.jme3.ai.navigation.detour.NavMesh;
import com.jme3.ai.navigation.detour.NavMesh;
import com.jme3.ai.navigation.detour.NavMeshQuery;
import com.jme3.ai.navigation.detour.QueryFilter;
import com.jme3.ai.navigation.utils.SWIGTYPE_p_float;
import com.jme3.ai.navigation.utils.RecastJNI;
import com.jme3.ai.navigation.utils.SWIGTYPE_p_unsigned_int;
import com.jme3.ai.navigation.utils.SWIGTYPE_p_int;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class dtPathQueue {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public dtPathQueue(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(dtPathQueue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RecastJNI.delete_dtPathQueue(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public dtPathQueue() {
    this(RecastJNI.new_dtPathQueue(), true);
  }

  public boolean init(int maxPathSize, int maxSearchNodeCount, NavMesh nav) {
    return RecastJNI.dtPathQueue_init(swigCPtr, this, maxPathSize, maxSearchNodeCount, NavMesh.getCPtr(nav), nav);
  }

  public void update(int maxIters) {
    RecastJNI.dtPathQueue_update(swigCPtr, this, maxIters);
  }

  public long request(long startRef, long endRef, SWIGTYPE_p_float startPos, SWIGTYPE_p_float endPos, QueryFilter filter) {
    return RecastJNI.dtPathQueue_request(swigCPtr, this, startRef, endRef, SWIGTYPE_p_float.getCPtr(startPos), SWIGTYPE_p_float.getCPtr(endPos), QueryFilter.getCPtr(filter), filter);
  }

  public long getRequestStatus(long ref) {
    return RecastJNI.dtPathQueue_getRequestStatus(swigCPtr, this, ref);
  }

  public long getPathResult(long ref, SWIGTYPE_p_unsigned_int path, SWIGTYPE_p_int pathSize, int maxPath) {
    return RecastJNI.dtPathQueue_getPathResult(swigCPtr, this, ref, SWIGTYPE_p_unsigned_int.getCPtr(path), SWIGTYPE_p_int.getCPtr(pathSize), maxPath);
  }

  public NavMeshQuery getNavQuery() {
    long cPtr = RecastJNI.dtPathQueue_getNavQuery(swigCPtr, this);
    return (cPtr == 0) ? null : new NavMeshQuery(cPtr, false);
  }

}
