package com.jme3.ai.navigation.crowd;


import com.jme3.ai.navigation.utils.RecastJNI;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class UpdateFlags {
  public final static UpdateFlags DT_CROWD_ANTICIPATE_TURNS = new UpdateFlags("DT_CROWD_ANTICIPATE_TURNS", RecastJNI.DT_CROWD_ANTICIPATE_TURNS_get());
  public final static UpdateFlags DT_CROWD_OBSTACLE_AVOIDANCE = new UpdateFlags("DT_CROWD_OBSTACLE_AVOIDANCE", RecastJNI.DT_CROWD_OBSTACLE_AVOIDANCE_get());
  public final static UpdateFlags DT_CROWD_SEPARATION = new UpdateFlags("DT_CROWD_SEPARATION", RecastJNI.DT_CROWD_SEPARATION_get());
  public final static UpdateFlags DT_CROWD_OPTIMIZE_VIS = new UpdateFlags("DT_CROWD_OPTIMIZE_VIS", RecastJNI.DT_CROWD_OPTIMIZE_VIS_get());
  public final static UpdateFlags DT_CROWD_OPTIMIZE_TOPO = new UpdateFlags("DT_CROWD_OPTIMIZE_TOPO", RecastJNI.DT_CROWD_OPTIMIZE_TOPO_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static UpdateFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + UpdateFlags.class + " with value " + swigValue);
  }

  private UpdateFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private UpdateFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private UpdateFlags(String swigName, UpdateFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static UpdateFlags[] swigValues = { DT_CROWD_ANTICIPATE_TURNS, DT_CROWD_OBSTACLE_AVOIDANCE, DT_CROWD_SEPARATION, DT_CROWD_OPTIMIZE_VIS, DT_CROWD_OPTIMIZE_TOPO };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

