package com.jme3.ai.navigation.recast;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
public final class AllocHint {

    public final static AllocHint RC_ALLOC_PERM = new AllocHint("RC_ALLOC_PERM");
    public final static AllocHint RC_ALLOC_TEMP = new AllocHint("RC_ALLOC_TEMP");

    public final int swigValue() {
        return swigValue;
    }

    @Override
    public String toString() {
        return swigName;
    }

    public static AllocHint swigToEnum(int swigValue) {
        if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue) {
            return swigValues[swigValue];
        }
        for (int i = 0; i < swigValues.length; i++) {
            if (swigValues[i].swigValue == swigValue) {
                return swigValues[i];
            }
        }
        throw new IllegalArgumentException("No enum " + AllocHint.class + " with value " + swigValue);
    }

    private AllocHint(String swigName) {
        this.swigName = swigName;
        this.swigValue = swigNext++;
    }

    private AllocHint(String swigName, int swigValue) {
        this.swigName = swigName;
        this.swigValue = swigValue;
        swigNext = swigValue + 1;
    }

    private AllocHint(String swigName, AllocHint swigEnum) {
        this.swigName = swigName;
        this.swigValue = swigEnum.swigValue;
        swigNext = this.swigValue + 1;
    }
    private static AllocHint[] swigValues = {RC_ALLOC_PERM, RC_ALLOC_TEMP};
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
}
